#+TITLE: Hello World
#+DRAFT: true
#+AUTHOR: V34L
#+DATE: 2023-11-15
#+HUGO_TAGS: linux

* How I started using Linux
** 2017
My journey started halfway through highschool, when I started exploring the "Deep Web" using Tails as a way to be more private while browsing with Tor. Being my first exposure to Linux, it was pretty positive and I didn't experience any friction trying to do the things I wanted to do.

Being an avid gamer at the time, I had no intention of daily driving a Linux distro, worried that I wouldn't be able to play my favourite online games. Daily driving would still have to wait a couple of years.

** 2020
It wasnt until 2020 that I installed my first /real/ distro : *Ubuntu*.
After the family iMac(2009) started slowing down significantly, I decided to put Ubuntu on it to try to extend it's lifespan.
During this time, I was taking college classes where we would configure switches and set up servers running Ubuntu server. Not knowing any other major distro, it seemed like an obvious choice.
With these classes, I was able to learn how the terminal worked and how to use my computer efficiently.

* 2022
