name: Build and Push Hugo to Harbor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_CREDENTIALS }}" | base64 --decode | \
          docker login -u $(echo "${{ secrets.HARBOR_CREDENTIALS }}" | base64 --decode | cut -d ':' -f1) \
          --password-stdin ${{ secrets.HARBOR_REGISTRY_URL }}

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE=${{ secrets.HARBOR_REGISTRY_URL }}/project-name/${{ github.repository }}:$COMMIT_SHA
          docker build -t $IMAGE -f ./Dockerfile .

      - name: Push image to Harbor
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker push ${{ secrets.HARBOR_REGISTRY_URL }}/project-name/${{ github.repository }}:$COMMIT_SHA
