name: Build and Push Hugo to Harbor

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: core.harbor.v34l.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image to Harbor
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: core.harbor.v34l.com/hugo/blog:latest
